In [1]:
# This is necessary to recognize the modules
import os
import sys
from decimal import Decimal
import warnings

warnings.filterwarnings("ignore")
root_path = os.path.abspath(os.path.join(os.getcwd(), '../..'))
sys.path.append(root_path)

In [2]:
from data_sources.clob import CLOBDataSource

clob = CLOBDataSource()

clob.load_candles_cache(root_path + "/data")
candles = {f"{key[0]}_{key[1]}_{key[2]}": value.data for key, value in clob.candles_cache.items()}
for key, df in candles.items():
    df.reset_index(inplace=True, drop=True)
    bb_columns = [col for col in df.columns if "bb" in col.lower() or col in ["signal", "out_of_bounds", "score"]]
    df.drop(columns=bb_columns, inplace=True)

In [3]:
candles["binance_perpetual_AMB-USDT_1m"]

,timestamp,open,high,low,close,volume,quote_asset_volume,n_trades,taker_buy_base_volume,taker_buy_quote_volume
0,1722538140,0.00776,0.007774,0.007751,0.007767,3152304,24480.955479,233,1899770,14754.437102
1,1722538200,0.007765,0.007792,0.00775,0.007767,6404259,49786.667518,313,4521135,35154.520589
2,1722538260,0.007766,0.007783,0.007748,0.007754,3684897,28620.657051,273,1241372,9644.82187
3,1722538320,0.007752,0.007769,0.007737,0.007763,3538512,27438.733944,243,1757762,13629.960631
4,1722538380,0.007766,0.007789,0.007757,0.007789,2609139,20276.626184,189,1486803,11561.975872
...,...,...,...,...,...,...,...,...,...,...
21596,1723834740,0.007461,0.007465,0.007454,0.007458,558861,4168.152006,65,124637,929.452565
21597,1723834800,0.007456,0.007468,0.007453,0.007462,2829741,21110.176395,187,1419107,10587.452583
21598,1723834860,0.00746,0.007477,0.007458,0.007473,4750291,35493.883637,190,3863692,28873.81254
21599,1723834920,0.007475,0.007491,0.007475,0.007484,1218556,9116.435043,114,501744,3753.289653
21600,1723834980,0.007484,0.007484,0.007484,0.007484,42325,316.7603,5,42325,316.7603

In [4]:
from hummingbot.strategy_v2.backtesting.controllers_backtesting.directional_trading_backtesting import \
    DirectionalTradingBacktesting
import os
import datetime

start_time = datetime.datetime(2024, 8, 1).timestamp()
end_time = datetime.datetime(2024, 8, 14).timestamp()

controllers_conf_dir_path = os.path.join(root_path, "research_notebooks", "xtreet_bb", "configs")
config_files = os.listdir(controllers_conf_dir_path)
backtesting_engine = DirectionalTradingBacktesting()
backtesting_engine.backtesting_data_provider.candles_feeds = candles
backtesting_engine.backtesting_data_provider.start_time = int(start_time)
backtesting_engine.backtesting_data_provider.end_time = int(end_time)

In [5]:
backtesting_engine.backtesting_data_provider.candles_feeds.keys()

dict_keys(['binance_perpetual_ZETA-USDT_3m', 'binance_perpetual_TIA-USDT_3m', 'binance_perpetual_REZ-USDT_3m', 'binance_perpetual_ETHFI-USDT_3m', 'binance_perpetual_LOOM-USDT_3m', 'binance_perpetual_PIXEL-USDT_1m', 'binance_perpetual_LPT-USDT_3m', 'binance_perpetual_CYBER-USDT_3m', 'binance_perpetual_ATOM-USDT_3m', 'binance_perpetual_ALGO-USDT_3m', 'binance_perpetual_TRU-USDT_3m', 'binance_perpetual_NOT-USDT_1m', 'binance_perpetual_KEY-USDT_1m', 'binance_perpetual_LSK-USDT_1m', 'binance_perpetual_RSR-USDT_3m', 'binance_perpetual_ENJ-USDT_1m', 'binance_perpetual_GAS-USDT_1m', 'binance_perpetual_CAKE-USDT_3m', 'binance_perpetual_AVAX-USDT_3m', 'binance_perpetual_C98-USDT_3m', 'binance_perpetual_MOVR-USDT_3m', 'binance_perpetual_ONT-USDT_3m', 'binance_perpetual_CHR-USDT_1m', 'binance_perpetual_SEI-USDT_1m', 'binance_perpetual_WIF-USDT_1m', 'binance_perpetual_1000SATS-USDT_1m', 'binance_perpetual_GLM-USDT_3m', 'binance_perpetual_LDO-USDT_1m', 'binance_perpetual_MEME-USDT_3m', 'binance_perpetual_TLM-USDT_1m', 'binance_perpetual_ENA-USDT_3m', 'binance_perpetual_LEVER-USDT_3m', 'binance_perpetual_REN-USDT_1m', 'binance_perpetual_DYDX-USDT_3m', 'binance_perpetual_1000XEC-USDT_3m', 'binance_perpetual_AGLD-USDT_3m', 'binance_perpetual_FET-USDT_3m', 'binance_perpetual_XEM-USDT_1m', 'binance_perpetual_POLYX-USDT_3m', 'binance_perpetual_HOOK-USDT_3m', 'binance_perpetual_PENDLE-USDT_1m', 'binance_perpetual_LUNA2-USDT_1m', 'binance_perpetual_FXS-USDT_3m', 'binance_perpetual_IOTX-USDT_1m', 'binance_perpetual_GALA-USDT_1m', 'binance_perpetual_MASK-USDT_1m', 'binance_perpetual_MTL-USDT_1m', 'binance_perpetual_XTZ-USDT_1m', 'binance_perpetual_WAXP-USDT_1m', 'binance_perpetual_LINA-USDT_1m', 'binance_perpetual_1INCH-USDT_3m', 'binance_perpetual_PEOPLE-USDT_3m', 'binance_perpetual_CFX-USDT_3m', 'binance_perpetual_DUSK-USDT_3m', 'binance_perpetual_COMBO-USDT_1m', 'binance_perpetual_G-USDT_3m', 'binance_perpetual_ARKM-USDT_3m', 'binance_perpetual_DENT-USDT_3m', 'binance_perpetual_ALICE-USDT_3m', 'binance_perpetual_BAT-USDT_1m', 'binance_perpetual_BOND-USDT_3m', 'binance_perpetual_HOT-USDT_3m', 'binance_perpetual_UMA-USDT_3m', 'binance_perpetual_ZIL-USDT_1m', 'binance_perpetual_FRONT-USDT_1m', 'binance_perpetual_BLUR-USDT_1m', 'binance_perpetual_ONG-USDT_3m', 'binance_perpetual_ACE-USDT_1m', 'binance_perpetual_BIGTIME-USDT_1m', 'binance_perpetual_AUCTION-USDT_1m', 'binance_perpetual_OMG-USDT_1m', 'binance_perpetual_CTSI-USDT_3m', 'binance_perpetual_AR-USDT_1m', 'binance_perpetual_HIGH-USDT_3m', 'binance_perpetual_ZRX-USDT_1m', 'binance_perpetual_BTCDOM-USDT_1m', 'binance_perpetual_ASTR-USDT_1m', 'binance_perpetual_AXL-USDT_3m', 'binance_perpetual_SYN-USDT_1m', 'binance_perpetual_MYRO-USDT_3m', 'binance_perpetual_RIF-USDT_3m', 'binance_perpetual_1000LUNC-USDT_3m', 'binance_perpetual_AEVO-USDT_1m', 'binance_perpetual_ATA-USDT_1m', 'binance_perpetual_VET-USDT_1m', 'binance_perpetual_BEL-USDT_1m', 'binance_perpetual_THETA-USDT_1m', 'binance_perpetual_ARPA-USDT_1m', 'binance_perpetual_ONE-USDT_1m', 'binance_perpetual_JOE-USDT_3m', 'binance_perpetual_BAL-USDT_3m', 'binance_perpetual_LISTA-USDT_3m', 'binance_perpetual_ZEC-USDT_1m', 'binance_perpetual_MINA-USDT_1m', 'binance_perpetual_AXS-USDT_3m', 'binance_perpetual_XVS-USDT_3m', 'binance_perpetual_POWR-USDT_1m', 'binance_perpetual_ORDI-USDT_3m', 'binance_perpetual_WLD-USDT_1m', 'binance_perpetual_1000BONK-USDT_3m', 'binance_perpetual_ICP-USDT_3m', 'binance_perpetual_FLM-USDT_1m', 'binance_perpetual_BAKE-USDT_3m', 'binance_perpetual_MANTA-USDT_1m', 'binance_perpetual_IMX-USDT_3m', 'binance_perpetual_MEW-USDT_1m', 'binance_perpetual_IOST-USDT_1m', 'binance_perpetual_SAND-USDT_1m', 'binance_perpetual_ILV-USDT_1m', 'binance_perpetual_ONDO-USDT_3m', 'binance_perpetual_1000RATS-USDT_1m', 'binance_perpetual_COMP-USDT_3m', 'binance_perpetual_ROSE-USDT_1m', 'binance_perpetual_T-USDT_3m', 'binance_perpetual_NEO-USDT_3m', 'binance_perpetual_GTC-USDT_1m', 'binance_perpetual_WOO-USDT_1m', 'binance_perpetual_OMNI-USDT_3m', 'binance_perpetual_NKN-USDT_3m', 'binance_perpetual_ORBS-USDT_3m', 'binance_perpetual_DOGE-USDT_3m', 'binance_perpetual_PYTH-USDT_3m', 'binance_perpetual_RLC-USDT_1m', 'binance_perpetual_FTM-USDT_1m', 'binance_perpetual_SPELL-USDT_1m', 'binance_perpetual_LIT-USDT_3m', 'binance_perpetual_NFP-USDT_1m', 'binance_perpetual_XVG-USDT_1m', 'binance_perpetual_USTC-USDT_1m', 'binance_perpetual_SKL-USDT_3m', 'binance_perpetual_APT-USDT_3m', 'binance_perpetual_METIS-USDT_3m', 'binance_perpetual_SOL-USDT_1m', 'binance_perpetual_GMX-USDT_3m', 'binance_perpetual_AAVE-USDT_1m', 'binance_perpetual_ANKR-USDT_3m', 'binance_perpetual_RUNE-USDT_1m', 'binance_perpetual_UNI-USDT_3m', 'binance_perpetual_LRC-USDT_3m', 'binance_perpetual_STX-USDT_1m', 'binance_perpetual_SUPER-USDT_1m', 'binance_perpetual_MANA-USDT_3m', 'binance_perpetual_SUSHI-USDT_3m', 'binance_perpetual_LQTY-USDT_1m', 'binance_perpetual_MAV-USDT_1m', 'binance_perpetual_ICX-USDT_1m', 'binance_perpetual_KLAY-USDT_3m', 'binance_perpetual_COTI-USDT_3m', 'binance_perpetual_ENS-USDT_1m', 'binance_perpetual_SUI-USDT_3m', 'binance_perpetual_OGN-USDT_1m', 'binance_perpetual_BLZ-USDT_3m', 'binance_perpetual_ZRO-USDT_3m', 'binance_perpetual_W-USDT_3m', 'binance_perpetual_STG-USDT_1m', 'binance_perpetual_EGLD-USDT_3m', 'binance_perpetual_SFP-USDT_3m', 'binance_perpetual_DAR-USDT_3m', 'binance_perpetual_XMR-USDT_3m', 'binance_perpetual_MATIC-USDT_3m', 'binance_perpetual_MAGIC-USDT_1m', 'binance_perpetual_DEFI-USDT_3m', 'binance_perpetual_UNFI-USDT_3m', 'binance_perpetual_BNT-USDT_3m', 'binance_perpetual_QNT-USDT_1m', 'binance_perpetual_OM-USDT_3m', 'binance_perpetual_RENDER-USDT_3m', 'binance_perpetual_DYM-USDT_3m', 'binance_perpetual_JTO-USDT_1m', 'binance_perpetual_OP-USDT_1m', 'binance_perpetual_XRP-USDT_1m', 'binance_perpetual_1000PEPE-USDT_3m', 'binance_perpetual_TNSR-USDT_1m', 'binance_perpetual_ALT-USDT_1m', 'binance_perpetual_TRX-USDT_1m', 'binance_perpetual_MAVIA-USDT_3m', 'binance_perpetual_BNB-USDT_3m', 'binance_perpetual_RVN-USDT_1m', 'binance_perpetual_XAI-USDT_1m', 'binance_perpetual_IOTA-USDT_1m', 'binance_perpetual_BEAMX-USDT_3m', 'binance_perpetual_STMX-USDT_3m', 'binance_perpetual_TWT-USDT_3m', 'binance_perpetual_DASH-USDT_1m', 'binance_perpetual_NTRN-USDT_1m', 'binance_perpetual_1000SHIB-USDT_1m', 'binance_perpetual_RONIN-USDT_1m', 'binance_perpetual_REEF-USDT_3m', 'binance_perpetual_PHB-USDT_3m', 'binance_perpetual_CKB-USDT_3m', 'binance_perpetual_PORTAL-USDT_3m', 'binance_perpetual_QTUM-USDT_3m', 'binance_perpetual_VANRY-USDT_3m', 'binance_perpetual_ADA-USDT_3m', 'binance_perpetual_ARK-USDT_1m', 'binance_perpetual_ETHW-USDT_3m', 'binance_perpetual_STRK-USDT_3m', 'binance_perpetual_OXT-USDT_1m', 'binance_perpetual_EOS-USDT_1m', 'binance_perpetual_API3-USDT_3m', 'binance_perpetual_BICO-USDT_3m', 'binance_perpetual_NMR-USDT_3m', 'binance_perpetual_BANANA-USDT_3m', 'binance_perpetual_APE-USDT_1m', 'binance_perpetual_AMB-USDT_1m', 'binance_perpetual_GMT-USDT_3m', 'binance_perpetual_HFT-USDT_1m', 'binance_perpetual_1000FLOKI-USDT_3m', 'binance_perpetual_INJ-USDT_3m', 'binance_perpetual_KAS-USDT_3m', 'binance_perpetual_BOME-USDT_3m', 'binance_perpetual_AI-USDT_3m', 'binance_perpetual_KNC-USDT_1m', 'binance_perpetual_TURBO-USDT_1m', 'binance_perpetual_SSV-USDT_3m', 'binance_perpetual_CHZ-USDT_3m', 'binance_perpetual_TRB-USDT_1m', 'binance_perpetual_ID-USDT_3m', 'binance_perpetual_BNX-USDT_3m', 'binance_perpetual_CELO-USDT_3m', 'binance_perpetual_XLM-USDT_3m', 'binance_perpetual_CELR-USDT_1m', 'binance_perpetual_STEEM-USDT_1m', 'binance_perpetual_HBAR-USDT_1m', 'binance_perpetual_RARE-USDT_1m', 'binance_perpetual_STORJ-USDT_1m', 'binance_perpetual_BAND-USDT_3m', 'binance_perpetual_SXP-USDT_3m', 'binance_perpetual_BB-USDT_3m', 'binance_perpetual_GRT-USDT_3m', 'binance_perpetual_TON-USDT_3m', 'binance_perpetual_IO-USDT_1m', 'binance_perpetual_FIL-USDT_1m', 'binance_perpetual_ACH-USDT_3m', 'binance_perpetual_JUP-USDT_1m', 'binance_perpetual_CRV-USDT_1m', 'binance_perpetual_ARB-USDT_1m', 'binance_perpetual_YGG-USDT_1m', 'binance_perpetual_FLOW-USDT_3m', 'binance_perpetual_PERP-USDT_1m', 'binance_perpetual_RDNT-USDT_3m', 'binance_perpetual_ALPHA-USDT_3m', 'binance_perpetual_YFI-USDT_3m', 'binance_perpetual_JASMY-USDT_1m', 'binance_perpetual_ZK-USDT_3m', 'binance_perpetual_BADGER-USDT_1m', 'binance_perpetual_USDC-USDT_3m', 'binance_perpetual_BSV-USDT_3m', 'binance_perpetual_EDU-USDT_1m', 'binance_perpetual_SNX-USDT_3m', 'binance_perpetual_DODOX-USDT_3m', 'binance_perpetual_KAVA-USDT_3m', 'binance_perpetual_KSM-USDT_1m', 'binance_perpetual_SAGA-USDT_3m', 'binance_perpetual_ZEN-USDT_3m', 'binance_perpetual_HIFI-USDT_1m', 'binance_perpetual_DOT-USDT_1m', 'binance_perpetual_NEAR-USDT_1m', 'binance_perpetual_TOKEN-USDT_3m', 'binance_perpetual_MKR-USDT_3m', 'binance_perpetual_TAO-USDT_3m', 'binance_perpetual_QNT-USDT_3m', 'binance_perpetual_BNT-USDT_1m', 'binance_perpetual_DEFI-USDT_1m', 'binance_perpetual_UNFI-USDT_1m', 'binance_perpetual_MAGIC-USDT_3m', 'binance_perpetual_XMR-USDT_1m', 'binance_perpetual_MATIC-USDT_1m', 'binance_perpetual_DAR-USDT_1m', 'binance_perpetual_SFP-USDT_1m', 'binance_perpetual_EGLD-USDT_1m', 'binance_perpetual_STG-USDT_3m', 'binance_perpetual_W-USDT_1m', 'binance_perpetual_ZRO-USDT_1m', 'binance_perpetual_BLZ-USDT_1m', 'binance_perpetual_OGN-USDT_3m', 'binance_perpetual_SUI-USDT_1m', 'binance_perpetual_COTI-USDT_1m', 'binance_perpetual_ENS-USDT_3m', 'binance_perpetual_ICX-USDT_3m', 'binance_perpetual_KLAY-USDT_1m', 'binance_perpetual_MAV-USDT_3m', 'binance_perpetual_LQTY-USDT_3m', 'binance_perpetual_SUSHI-USDT_1m', 'binance_perpetual_SUPER-USDT_3m', 'binance_perpetual_MANA-USDT_1m', 'binance_perpetual_STX-USDT_3m', 'binance_perpetual_LRC-USDT_1m', 'binance_perpetual_UNI-USDT_1m', 'binance_perpetual_RUNE-USDT_3m', 'binance_perpetual_ANKR-USDT_1m', 'binance_perpetual_GMX-USDT_1m', 'binance_perpetual_AAVE-USDT_3m', 'binance_perpetual_METIS-USDT_1m', 'binance_perpetual_APT-USDT_1m', 'binance_perpetual_SOL-USDT_3m', 'binance_perpetual_SKL-USDT_1m', 'binance_perpetual_QTUM-USDT_1m', 'binance_perpetual_VANRY-USDT_1m', 'binance_perpetual_PORTAL-USDT_1m', 'binance_perpetual_CKB-USDT_1m', 'binance_perpetual_PHB-USDT_1m', 'binance_perpetual_RONIN-USDT_3m', 'binance_perpetual_REEF-USDT_1m', 'binance_perpetual_1000SHIB-USDT_3m', 'binance_perpetual_DASH-USDT_3m', 'binance_perpetual_NTRN-USDT_3m', 'binance_perpetual_STMX-USDT_1m', 'binance_perpetual_TWT-USDT_1m', 'binance_perpetual_BEAMX-USDT_1m', 'binance_perpetual_XAI-USDT_3m', 'binance_perpetual_IOTA-USDT_3m', 'binance_perpetual_RVN-USDT_3m', 'binance_perpetual_BNB-USDT_1m', 'binance_perpetual_MAVIA-USDT_1m', 'binance_perpetual_ALT-USDT_3m', 'binance_perpetual_TRX-USDT_3m', 'binance_perpetual_1000PEPE-USDT_1m', 'binance_perpetual_TNSR-USDT_3m', 'binance_perpetual_XRP-USDT_3m', 'binance_perpetual_OP-USDT_3m', 'binance_perpetual_RENDER-USDT_1m', 'binance_perpetual_DYM-USDT_1m', 'binance_perpetual_JTO-USDT_3m', 'binance_perpetual_OM-USDT_1m', 'binance_perpetual_RARE-USDT_3m', 'binance_perpetual_BAND-USDT_1m', 'binance_perpetual_STORJ-USDT_3m', 'binance_perpetual_HBAR-USDT_3m', 'binance_perpetual_STEEM-USDT_3m', 'binance_perpetual_CELR-USDT_3m', 'binance_perpetual_CELO-USDT_1m', 'binance_perpetual_XLM-USDT_1m', 'binance_perpetual_BNX-USDT_1m', 'binance_perpetual_ID-USDT_1m', 'binance_perpetual_SSV-USDT_1m', 'binance_perpetual_TRB-USDT_3m', 'binance_perpetual_CHZ-USDT_1m', 'binance_perpetual_TURBO-USDT_3m', 'binance_perpetual_KNC-USDT_3m', 'binance_perpetual_AI-USDT_1m', 'binance_perpetual_BOME-USDT_1m', 'binance_perpetual_KAS-USDT_1m', 'binance_perpetual_INJ-USDT_1m', 'binance_perpetual_1000FLOKI-USDT_1m', 'binance_perpetual_HFT-USDT_3m', 'binance_perpetual_GMT-USDT_1m', 'binance_perpetual_AMB-USDT_3m', 'binance_perpetual_APE-USDT_3m', 'binance_perpetual_BANANA-USDT_1m', 'binance_perpetual_NMR-USDT_1m', 'binance_perpetual_BICO-USDT_1m', 'binance_perpetual_API3-USDT_1m', 'binance_perpetual_EOS-USDT_3m', 'binance_perpetual_OXT-USDT_3m', 'binance_perpetual_STRK-USDT_1m', 'binance_perpetual_ARK-USDT_3m', 'binance_perpetual_ETHW-USDT_1m', 'binance_perpetual_ADA-USDT_1m', 'binance_perpetual_TAO-USDT_1m', 'binance_perpetual_MKR-USDT_1m', 'binance_perpetual_TOKEN-USDT_1m', 'binance_perpetual_NEAR-USDT_3m', 'binance_perpetual_DOT-USDT_3m', 'binance_perpetual_HIFI-USDT_3m', 'binance_perpetual_ZEN-USDT_1m', 'binance_perpetual_SAGA-USDT_1m', 'binance_perpetual_KSM-USDT_3m', 'binance_perpetual_SNX-USDT_1m', 'binance_perpetual_KAVA-USDT_1m', 'binance_perpetual_DODOX-USDT_1m', 'binance_perpetual_BSV-USDT_1m', 'binance_perpetual_EDU-USDT_3m', 'binance_perpetual_BADGER-USDT_3m', 'binance_perpetual_USDC-USDT_1m', 'binance_perpetual_ZK-USDT_1m', 'binance_perpetual_JASMY-USDT_3m', 'binance_perpetual_YFI-USDT_1m', 'binance_perpetual_PERP-USDT_3m', 'binance_perpetual_RDNT-USDT_1m', 'binance_perpetual_ALPHA-USDT_1m', 'binance_perpetual_FLOW-USDT_1m', 'binance_perpetual_YGG-USDT_3m', 'binance_perpetual_ARB-USDT_3m', 'binance_perpetual_CRV-USDT_3m', 'binance_perpetual_JUP-USDT_3m', 'binance_perpetual_ACH-USDT_1m', 'binance_perpetual_FIL-USDT_3m', 'binance_perpetual_TON-USDT_1m', 'binance_perpetual_GRT-USDT_1m', 'binance_perpetual_IO-USDT_3m', 'binance_perpetual_BB-USDT_1m', 'binance_perpetual_SXP-USDT_1m', 'binance_perpetual_TLM-USDT_3m', 'binance_perpetual_GLM-USDT_1m', 'binance_perpetual_MEME-USDT_1m', 'binance_perpetual_LDO-USDT_3m', 'binance_perpetual_1000SATS-USDT_3m', 'binance_perpetual_WIF-USDT_3m', 'binance_perpetual_CHR-USDT_3m', 'binance_perpetual_SEI-USDT_3m', 'binance_perpetual_ONT-USDT_1m', 'binance_perpetual_MOVR-USDT_1m', 'binance_perpetual_C98-USDT_1m', 'binance_perpetual_AVAX-USDT_1m', 'binance_perpetual_CAKE-USDT_1m', 'binance_perpetual_GAS-USDT_3m', 'binance_perpetual_ENJ-USDT_3m', 'binance_perpetual_LSK-USDT_3m', 'binance_perpetual_RSR-USDT_1m', 'binance_perpetual_KEY-USDT_3m', 'binance_perpetual_NOT-USDT_3m', 'binance_perpetual_TRU-USDT_1m', 'binance_perpetual_ALGO-USDT_1m', 'binance_perpetual_ATOM-USDT_1m', 'binance_perpetual_CYBER-USDT_1m', 'binance_perpetual_LPT-USDT_1m', 'binance_perpetual_PIXEL-USDT_3m', 'binance_perpetual_LOOM-USDT_1m', 'binance_perpetual_REZ-USDT_1m', 'binance_perpetual_ETHFI-USDT_1m', 'binance_perpetual_TIA-USDT_1m', 'binance_perpetual_ZETA-USDT_1m', 'binance_perpetual_HOT-USDT_1m', 'binance_perpetual_BOND-USDT_1m', 'binance_perpetual_BAT-USDT_3m', 'binance_perpetual_DENT-USDT_1m', 'binance_perpetual_ALICE-USDT_1m', 'binance_perpetual_ARKM-USDT_1m', 'binance_perpetual_G-USDT_1m', 'binance_perpetual_DUSK-USDT_1m', 'binance_perpetual_COMBO-USDT_3m', 'binance_perpetual_CFX-USDT_1m', 'binance_perpetual_PEOPLE-USDT_1m', 'binance_perpetual_LINA-USDT_3m', 'binance_perpetual_1INCH-USDT_1m', 'binance_perpetual_WAXP-USDT_3m', 'binance_perpetual_XTZ-USDT_3m', 'binance_perpetual_MTL-USDT_3m', 'binance_perpetual_GALA-USDT_3m', 'binance_perpetual_MASK-USDT_3m', 'binance_perpetual_IOTX-USDT_3m', 'binance_perpetual_LUNA2-USDT_3m', 'binance_perpetual_FXS-USDT_1m', 'binance_perpetual_PENDLE-USDT_3m', 'binance_perpetual_HOOK-USDT_1m', 'binance_perpetual_FET-USDT_1m', 'binance_perpetual_POLYX-USDT_1m', 'binance_perpetual_XEM-USDT_3m', 'binance_perpetual_AGLD-USDT_1m', 'binance_perpetual_1000XEC-USDT_1m', 'binance_perpetual_DYDX-USDT_1m', 'binance_perpetual_REN-USDT_3m', 'binance_perpetual_LEVER-USDT_1m', 'binance_perpetual_ENA-USDT_1m', 'binance_perpetual_FLM-USDT_3m', 'binance_perpetual_ICP-USDT_1m', 'binance_perpetual_1000BONK-USDT_1m', 'binance_perpetual_ORDI-USDT_1m', 'binance_perpetual_WLD-USDT_3m', 'binance_perpetual_POWR-USDT_3m', 'binance_perpetual_XVS-USDT_1m', 'binance_perpetual_AXS-USDT_1m', 'binance_perpetual_MINA-USDT_3m', 'binance_perpetual_ZEC-USDT_3m', 'binance_perpetual_LISTA-USDT_1m', 'binance_perpetual_BAL-USDT_1m', 'binance_perpetual_JOE-USDT_1m', 'binance_perpetual_ARPA-USDT_3m', 'binance_perpetual_ONE-USDT_3m', 'binance_perpetual_THETA-USDT_3m', 'binance_perpetual_BEL-USDT_3m', 'binance_perpetual_VET-USDT_3m', 'binance_perpetual_ATA-USDT_3m', 'binance_perpetual_AEVO-USDT_3m', 'binance_perpetual_RIF-USDT_1m', 'binance_perpetual_MYRO-USDT_1m', 'binance_perpetual_1000LUNC-USDT_1m', 'binance_perpetual_SYN-USDT_3m', 'binance_perpetual_AXL-USDT_1m', 'binance_perpetual_ASTR-USDT_3m', 'binance_perpetual_BTCDOM-USDT_3m', 'binance_perpetual_ZRX-USDT_3m', 'binance_perpetual_HIGH-USDT_1m', 'binance_perpetual_AR-USDT_3m', 'binance_perpetual_CTSI-USDT_1m', 'binance_perpetual_OMG-USDT_3m', 'binance_perpetual_AUCTION-USDT_3m', 'binance_perpetual_BIGTIME-USDT_3m', 'binance_perpetual_ONG-USDT_1m', 'binance_perpetual_ACE-USDT_3m', 'binance_perpetual_BLUR-USDT_3m', 'binance_perpetual_FRONT-USDT_3m', 'binance_perpetual_ZIL-USDT_3m', 'binance_perpetual_UMA-USDT_1m', 'binance_perpetual_USTC-USDT_3m', 'binance_perpetual_XVG-USDT_3m', 'binance_perpetual_NFP-USDT_3m', 'binance_perpetual_SPELL-USDT_3m', 'binance_perpetual_LIT-USDT_1m', 'binance_perpetual_FTM-USDT_3m', 'binance_perpetual_PYTH-USDT_1m', 'binance_perpetual_RLC-USDT_3m', 'binance_perpetual_DOGE-USDT_1m', 'binance_perpetual_ORBS-USDT_1m', 'binance_perpetual_NKN-USDT_1m', 'binance_perpetual_OMNI-USDT_1m', 'binance_perpetual_GTC-USDT_3m', 'binance_perpetual_WOO-USDT_3m', 'binance_perpetual_NEO-USDT_1m', 'binance_perpetual_T-USDT_1m', 'binance_perpetual_COMP-USDT_1m', 'binance_perpetual_ROSE-USDT_3m', 'binance_perpetual_1000RATS-USDT_3m', 'binance_perpetual_ONDO-USDT_1m', 'binance_perpetual_ILV-USDT_3m', 'binance_perpetual_SAND-USDT_3m', 'binance_perpetual_IOST-USDT_3m', 'binance_perpetual_MEW-USDT_3m', 'binance_perpetual_IMX-USDT_1m', 'binance_perpetual_MANTA-USDT_3m', 'binance_perpetual_BAKE-USDT_1m'])

In [6]:
backtesting_engine.backtesting_data_provider.candles_feeds["binance_perpetual_AMB-USDT_1m"]

,timestamp,open,high,low,close,volume,quote_asset_volume,n_trades,taker_buy_base_volume,taker_buy_quote_volume
0,1722538140,0.00776,0.007774,0.007751,0.007767,3152304,24480.955479,233,1899770,14754.437102
1,1722538200,0.007765,0.007792,0.00775,0.007767,6404259,49786.667518,313,4521135,35154.520589
2,1722538260,0.007766,0.007783,0.007748,0.007754,3684897,28620.657051,273,1241372,9644.82187
3,1722538320,0.007752,0.007769,0.007737,0.007763,3538512,27438.733944,243,1757762,13629.960631
4,1722538380,0.007766,0.007789,0.007757,0.007789,2609139,20276.626184,189,1486803,11561.975872
...,...,...,...,...,...,...,...,...,...,...
21596,1723834740,0.007461,0.007465,0.007454,0.007458,558861,4168.152006,65,124637,929.452565
21597,1723834800,0.007456,0.007468,0.007453,0.007462,2829741,21110.176395,187,1419107,10587.452583
21598,1723834860,0.00746,0.007477,0.007458,0.007473,4750291,35493.883637,190,3863692,28873.81254
21599,1723834920,0.007475,0.007491,0.007475,0.007484,1218556,9116.435043,114,501744,3753.289653
21600,1723834980,0.007484,0.007484,0.007484,0.007484,42325,316.7603,5,42325,316.7603

In [7]:
bt_results = {}
config_file = "xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.012_0.014_0.019_50_1.0_0.011716159457667042.yml"
config = backtesting_engine.get_controller_config_instance_from_yml(
    config_path=config_file,
    controllers_conf_dir_path=controllers_conf_dir_path,
    controllers_module="controllers")
backtesting_results = await backtesting_engine.run_backtesting(
    controller_config=config, trade_cost=0.0006,
    start=int(start_time), end=int(end_time), backtesting_resolution="1m")
df = backtesting_results["processed_data"]["features"]
executors = backtesting_results["executors"]
results = backtesting_results["results"]
print(f"Net PNL quote: {results['net_pnl_quote']} | Total Volume: {results['total_volume']} ")
bt_results[config_file] = {"df": df, "executors": executors, "results": results, "config": config}

Net PNL quote: -5.028775777176928 | Total Volume: 52831.656962605

In [8]:
bt_results[config_file]["df"]

,timestamp_bt,open_bt,high_bt,low_bt,close_bt,volume_bt,quote_asset_volume_bt,n_trades_bt,taker_buy_base_volume_bt,taker_buy_quote_volume_bt,...,quote_asset_volume,n_trades,taker_buy_base_volume,taker_buy_quote_volume,BBL_50_1.0,BBM_50_1.0,BBU_50_1.0,BBB_50_1.0,BBP_50_1.0,signal
49,1722542100,0.01524,0.015257,0.015225,0.015225,8788390,133986.739311,396,6589011,100460.350715,...,133986.739311,396,6589011,100460.350715,0.01512736,0.01516692,0.01520648,0.52162161,1.23413112,-1
50,1722542160,0.015224,0.015247,0.015222,0.01524,2224175,33886.666222,204,1157934,17640.188463,...,33886.666222,204,1157934,17640.188463,0.01512887,0.01516924,0.01520961,0.53219691,1.37649945,-1
51,1722542220,0.015241,0.015251,0.015241,0.015248,1496985,22822.03751,125,918327,13999.284266,...,22822.03751,125,918327,13999.284266,0.01513068,0.01517184,0.015213,0.54258236,1.42517313,-1
52,1722542280,0.015247,0.015248,0.015232,0.015245,1801464,27454.533632,181,975247,14864.648896,...,27454.533632,181,975247,14864.648896,0.0151328,0.01517442,0.01521604,0.54854511,1.34792454,-1
53,1722542340,0.015245,0.015251,0.015241,0.015242,1553310,23681.630215,175,1239176,18892.443888,...,23681.630215,175,1239176,18892.443888,0.01513488,0.01517684,0.0152188,0.55293723,1.27646858,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17738,1723604160,0.013834,0.013836,0.013833,0.013836,1392403,19263.422124,104,597544,8267.091716,...,19263.422124,104,597544,8267.091716,0.01381571,0.01382706,0.01383841,0.16411596,0.89396428,0
17739,1723604220,0.013836,0.013836,0.013831,0.013831,825427,11418.502691,117,37633,520.577289,...,11418.502691,117,37633,520.577289,0.01381649,0.01382752,0.01383855,0.15947705,0.65781081,0
17740,1723604280,0.013831,0.013832,0.013829,0.013831,708353,9797.135429,60,268832,3718.271038,...,9797.135429,60,268832,3718.271038,0.01381683,0.01382778,0.01383873,0.15839605,0.64701412,0
17741,1723604340,0.013831,0.013832,0.013827,0.013827,400415,5537.710802,65,45611,630.840686,...,5537.710802,65,45611,630.840686,0.01381706,0.01382794,0.01383882,0.15736389,0.45680184,0
17742,1723604400,0.013828,0.013845,0.013828,0.013845,2066595,28599.943547,258,1859769,25737.708239,...,28599.943547,258,1859769,25737.708239,0.01381714,0.01382828,0.01383942,0.16110741,1.25050326,-1

In [15]:
bt_results = {}

for i, config_file in enumerate(config_files):
    print(f"Experiment {i}/{len(config_files)}: {config_file}")
    try:
        config = backtesting_engine.get_controller_config_instance_from_yml(
            config_path=config_file,
            controllers_conf_dir_path=controllers_conf_dir_path,
            controllers_module="controllers")
        backtesting_results = await backtesting_engine.run_backtesting(
            controller_config=config, trade_cost=0.0006,
            start=int(start_time), end=int(end_time), backtesting_resolution="1m")
        df = backtesting_results["processed_data"]["features"]
        executors = backtesting_results["executors"]
        results = backtesting_results["results"]
        print(f"Net PNL quote: {results['net_pnl_quote']} | Total Volume: {results['total_volume']} ")
        bt_results[config_file] = {"df": df, "executors": executors, "results": results, "config": config}
    except:
        print(f"Error with {config_file}")

Experiment 0/600: xtreet_bb_binance_perpetual_1m_XMR-USDT_0.0_0.114_0.009_0.02_50_1.0_0.029853195572199086.yml
Net PNL quote: -2.7549902085099385 | Total Volume: 8249.589674903784
Experiment 1/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.051_0.02_0.036_200_1.0_0.05137503777576294.yml
Net PNL quote: -15.165885018667524 | Total Volume: 22830.94385212204
Experiment 2/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.017_0.026_200_1.0_0.03844208396560448.yml
Net PNL quote: -0.0778658409075687 | Total Volume: 2034.305450967238
Experiment 3/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.02_0.015_0.02_50_2.0_0.045337016856606044.yml
Net PNL quote: -110.44877394039135 | Total Volume: 35274.882465666364
Experiment 4/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.239_0.012_0.02_200_2.0_0.05137503777576294.yml
Net PNL quote: -1.3530704093098356 | Total Volume: 1654.1391718806215
Experiment 5/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.017_0.026_200_2.0_0.03844208396560448.yml
Net PNL quote: -10.47520420092396 | Total Volume: 13754.796756109667
Experiment 6/600: xtreet_bb_binance_perpetual_1m_LSK-USDT_0.0_0.037_0.014_0.021_200_2.0_0.03714784343056587.yml
Net PNL quote: -15.89049068261248 | Total Volume: 12970.799535196194
Experiment 7/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.298_0.017_0.02_200_1.0_0.04292421193829648.yml
Net PNL quote: -0.22343677031932918 | Total Volume: 623.874508181899
Experiment 8/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.014_0.028_200_2.0_0.04589832515176393.yml
Net PNL quote: -20.500015349364674 | Total Volume: 16973.753024339963
Experiment 9/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.017_0.026_50_1.0_0.017892644135188884.yml
Net PNL quote: -15.74365048381249 | Total Volume: 24222.90732879792
Experiment 10/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.012_0.017_200_2.0_0.017892644135188884.yml
Net PNL quote: 0.8512321197347873 | Total Volume: 1089.248789730666
Experiment 11/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.032_0.007_0.014_200_2.0_0.031763705229864075.yml
Net PNL quote: 0.3813729262227173 | Total Volume: 15794.320520745363
Experiment 12/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.045_0.015_0.02_50_2.0_0.045337016856606044.yml
Net PNL quote: -89.15069698890092 | Total Volume: 15891.63426688022
Experiment 13/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.022_0.028_200_2.0_0.04589832515176393.yml
Net PNL quote: -39.03869700719067 | Total Volume: 9114.283376745294
Experiment 14/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.043_0.012_0.017_50_1.0_0.01146650573325281.yml
Net PNL quote: -21.071724777759826 | Total Volume: 17026.45853375671
Experiment 15/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.298_0.012_0.02_200_1.0_0.01146650573325281.yml
Net PNL quote: -0.5070876197889423 | Total Volume: 1833.5223995221102
Experiment 16/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.017_0.014_0.022_200_2.0_0.017426913099682723.yml
Net PNL quote: 18.044620223224165 | Total Volume: 24922.8330511722
Experiment 17/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.224_0.016_0.028_200_2.0_0.009851989206577101.yml
Net PNL quote: 5.070198296201323 | Total Volume: 2520.9606314858097
Experiment 18/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.012_0.026_50_2.0_0.03844208396560448.yml
Net PNL quote: -1.2534831997251035 | Total Volume: 3827.0067906628924
Experiment 19/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.395_0.02_0.029_200_1.0_0.045337016856606044.yml
Net PNL quote: -2.7169685689868444 | Total Volume: 1199.4752145873292
Experiment 20/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.04_0.022_0.028_50_1.0_0.0400920938386012.yml
Net PNL quote: -6.566010425679539 | Total Volume: 16408.078500796888
Experiment 21/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.012_0.026_50_2.0_0.017892644135188884.yml
Net PNL quote: -1.2534831997251035 | Total Volume: 3827.0067906628924
Experiment 22/600: xtreet_bb_binance_perpetual_1m_XMR-USDT_0.0_0.114_0.015_0.02_200_1.0_0.008574241930863147.yml
Net PNL quote: -2.6682263108846467 | Total Volume: 2692.8069646390613
Experiment 23/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.034_0.008_0.01_200_2.0_0.013525179856115217.yml
Net PNL quote: -1.1381726402428427 | Total Volume: 7620.515974798057
Experiment 24/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.012_0.017_50_2.0_0.017892644135188884.yml
Net PNL quote: 19.524305580927866 | Total Volume: 16456.325602947403
Experiment 25/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.02_0.015_0.02_50_1.0_0.01966496722505456.yml
Net PNL quote: 7.843531551487123 | Total Volume: 43405.89214834146
Experiment 26/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.395_0.015_0.02_50_2.0_0.01966496722505456.yml
Net PNL quote: -2.4310426259445688 | Total Volume: 914.8798778548737
Experiment 27/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.022_0.028_200_1.0_0.017426913099682723.yml
Net PNL quote: -11.977384936394904 | Total Volume: 13204.144411554336
Experiment 28/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.017_0.026_50_1.0_0.03844208396560448.yml
Net PNL quote: -22.720489138725522 | Total Volume: 23506.08564944962
Experiment 29/600: xtreet_bb_binance_perpetual_1m_XMR-USDT_0.0_0.03_0.009_0.015_50_1.0_0.029853195572199086.yml
Net PNL quote: -49.266658120891506 | Total Volume: 22074.774094889322
Experiment 30/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.014_0.01_0.016_50_2.0_0.013525179856115217.yml
Net PNL quote: -33.88612412118587 | Total Volume: 42239.17032718121
Experiment 31/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.043_0.017_0.02_50_1.0_0.01146650573325281.yml
Net PNL quote: -2.2732491989664565 | Total Volume: 13834.757162339994
Experiment 32/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.224_0.016_0.022_50_1.0_0.0400920938386012.yml
Net PNL quote: 0.8351901336600508 | Total Volume: 2079.0825241443704
Experiment 33/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.043_0.017_0.02_200_1.0_0.01146650573325281.yml
Net PNL quote: -11.21340113687738 | Total Volume: 9059.956356537752
Experiment 34/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.034_0.01_0.016_200_1.0_0.013525179856115217.yml
Net PNL quote: -11.603794490138933 | Total Volume: 14398.05251185494
Experiment 35/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.034_0.01_0.016_50_1.0_0.034125533211456394.yml
Net PNL quote: -7.028576287720921 | Total Volume: 20376.823397251792
Experiment 36/600: xtreet_bb_binance_perpetual_1m_LSK-USDT_0.0_0.037_0.014_0.025_50_1.0_0.00857843137254894.yml
Net PNL quote: -14.44896524878811 | Total Volume: 27113.519334534765
Experiment 37/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.298_0.012_0.017_50_1.0_0.04292421193829648.yml
Net PNL quote: -0.7649685026023598 | Total Volume: 1332.2297380197815
Experiment 38/600: xtreet_bb_binance_perpetual_1m_LSK-USDT_0.0_0.22_0.021_0.025_50_2.0_0.03714784343056587.yml
Net PNL quote: -0.071354483983094 | Total Volume: 985.9845982701181
Experiment 39/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.043_0.012_0.02_200_1.0_0.04292421193829648.yml
Net PNL quote: -34.46923329486031 | Total Volume: 18093.972351021916
Experiment 40/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.043_0.012_0.017_200_1.0_0.04292421193829648.yml
Net PNL quote: -33.026133255039795 | Total Volume: 13917.324268089244
Experiment 41/600: xtreet_bb_binance_perpetual_1m_XMR-USDT_0.0_0.03_0.015_0.02_50_1.0_0.008574241930863147.yml
Net PNL quote: -13.20651175296888 | Total Volume: 16855.48170108884
Experiment 42/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.224_0.016_0.028_200_2.0_0.0400920938386012.yml
Net PNL quote: 5.070198296201323 | Total Volume: 2520.9606314858097
Experiment 43/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.298_0.017_0.02_50_2.0_0.01146650573325281.yml
Net PNL quote: -0.8899410316770064 | Total Volume: 656.3679721497064
Experiment 44/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.051_0.012_0.02_50_2.0_0.05137503777576294.yml
Net PNL quote: 15.062448335767172 | Total Volume: 17138.53066670864
Experiment 45/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.017_0.014_0.022_200_2.0_0.04589832515176393.yml
Net PNL quote: -11.240056153173411 | Total Volume: 28062.271426299616
Experiment 46/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.051_0.012_0.036_50_2.0_0.05137503777576294.yml
Net PNL quote: -12.45646963106342 | Total Volume: 39416.41423251677
Experiment 47/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.249_0.008_0.016_200_2.0_0.013525179856115217.yml
Net PNL quote: -0.6857934491306736 | Total Volume: 1799.4568790429169
Experiment 48/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.012_0.026_50_1.0_0.017892644135188884.yml
Net PNL quote: -4.288563394655963 | Total Volume: 36949.65313489983
Experiment 49/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.224_0.016_0.022_200_2.0_0.0400920938386012.yml
Net PNL quote: 2.6391343773452602 | Total Volume: 1312.2078226157091
Experiment 50/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.012_0.017_50_1.0_0.017892644135188884.yml
Net PNL quote: -0.30605695071856914 | Total Volume: 1627.6131340803056
Experiment 51/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.374_0.022_0.028_50_1.0_0.017426913099682723.yml
Net PNL quote: -1.8118307359167376 | Total Volume: 1190.317926984722
Experiment 52/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.051_0.02_0.036_200_2.0_0.042133463224549535.yml
Net PNL quote: -29.70668214598492 | Total Volume: 16605.72934027612
Experiment 53/600: xtreet_bb_binance_perpetual_1m_LSK-USDT_0.0_0.037_0.014_0.021_50_1.0_0.03714784343056587.yml
Net PNL quote: -17.841277421429226 | Total Volume: 19368.661902644326
Experiment 54/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.014_0.008_0.01_50_2.0_0.034125533211456394.yml
Net PNL quote: -27.09023455564407 | Total Volume: 38467.71507863165
Experiment 55/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.012_0.017_200_1.0_0.03844208396560448.yml
Net PNL quote: -22.605791793664945 | Total Volume: 13321.354561187716
Experiment 56/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.395_0.015_0.02_200_1.0_0.01966496722505456.yml
Net PNL quote: -1.6152669809646218 | Total Volume: 848.9425893608287
Experiment 57/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.012_0.026_200_2.0_0.03844208396560448.yml
Net PNL quote: 1.0374401327909033 | Total Volume: 20530.73765493799
Experiment 58/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.395_0.015_0.029_200_2.0_0.045337016856606044.yml
Net PNL quote: -3.2434007606620554 | Total Volume: 1523.3797645068448
Experiment 59/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.034_0.008_0.01_50_1.0_0.013525179856115217.yml
Net PNL quote: 2.447996640150517 | Total Volume: 15006.750033514056
Experiment 60/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.012_0.026_200_1.0_0.03844208396560448.yml
Net PNL quote: -0.8412030863698472 | Total Volume: 3594.058551231238
Experiment 61/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.012_0.017_200_2.0_0.03844208396560448.yml
Net PNL quote: 0.8512321197347873 | Total Volume: 1089.248789730666
Experiment 62/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.018_0.012_0.017_50_1.0_0.03844208396560448.yml
Net PNL quote: -22.93267297499991 | Total Volume: 42597.988824227126
Experiment 63/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.012_0.014_0.019_200_2.0_0.011716159457667042.yml
Net PNL quote: 20.484374602590858 | Total Volume: 27805.307041465312
Experiment 64/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.022_0.028_50_2.0_0.04589832515176393.yml
Net PNL quote: -16.882058346556082 | Total Volume: 12982.485010654309
Experiment 65/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.374_0.014_0.022_200_1.0_0.04589832515176393.yml
Net PNL quote: 0.24023777581355535 | Total Volume: 1423.7059403598894
Experiment 66/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.259_0.007_0.014_50_2.0_0.011716159457667042.yml
Net PNL quote: -0.9440520849433052 | Total Volume: 1892.3196762622676
Experiment 67/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.011_0.017_0.02_50_1.0_0.01146650573325281.yml
Net PNL quote: -55.73850652835775 | Total Volume: 47517.91535593687
Experiment 68/600: xtreet_bb_binance_perpetual_1m_XMR-USDT_0.0_0.114_0.009_0.02_200_1.0_0.029853195572199086.yml
Net PNL quote: -5.399012002869543 | Total Volume: 6388.779973797667
Experiment 69/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.251_0.017_0.026_50_2.0_0.017892644135188884.yml
Net PNL quote: -1.755519549808442 | Total Volume: 2055.0636698546587
Experiment 70/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.051_0.012_0.02_200_2.0_0.05137503777576294.yml
Net PNL quote: -36.01421352395734 | Total Volume: 10147.872973941512
Experiment 71/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.014_0.01_0.016_200_1.0_0.034125533211456394.yml
Net PNL quote: -33.543783453348915 | Total Volume: 39395.357003565434
Experiment 72/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.224_0.022_0.028_50_2.0_0.0400920938386012.yml
Net PNL quote: 1.6748672931656732 | Total Volume: 1538.4126658346736
Experiment 73/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.374_0.014_0.028_50_1.0_0.017426913099682723.yml
Net PNL quote: -0.18978620299983126 | Total Volume: 3113.396541633645
Experiment 74/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.014_0.022_50_2.0_0.017426913099682723.yml
Net PNL quote: -8.982506810877977 | Total Volume: 16374.723526540341
Experiment 75/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.259_0.014_0.019_50_2.0_0.031763705229864075.yml
Net PNL quote: -0.8217927168816536 | Total Volume: 1280.1351925634574
Experiment 76/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.239_0.02_0.036_200_1.0_0.05137503777576294.yml
Net PNL quote: -2.246318955426963 | Total Volume: 4109.94808442887
Experiment 77/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.051_0.012_0.036_50_1.0_0.042133463224549535.yml
Net PNL quote: -8.563625567986302 | Total Volume: 49986.31803603419
Experiment 78/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.239_0.02_0.036_200_2.0_0.042133463224549535.yml
Net PNL quote: -3.7987600376380986 | Total Volume: 3082.4610633216525
Experiment 79/600: xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.038_0.012_0.026_200_1.0_0.017892644135188884.yml
Net PNL quote: 12.069761327790813 | Total Volume: 25420.770220757808
Experiment 80/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.239_0.012_0.036_50_2.0_0.05137503777576294.yml
Net PNL quote: -0.6700740644159661 | Total Volume: 7538.160116515573
Experiment 81/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.045_0.02_0.029_50_1.0_0.01966496722505456.yml
Net PNL quote: -35.80152207796883 | Total Volume: 21577.14287759461
Experiment 82/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.045_0.015_0.029_200_1.0_0.045337016856606044.yml
Net PNL quote: -62.329400979702726 | Total Volume: 22649.48972409484
Experiment 83/600: xtreet_bb_binance_perpetual_1m_XMR-USDT_0.0_0.114_0.009_0.015_200_1.0_0.008574241930863147.yml
Net PNL quote: -2.8786909947699755 | Total Volume: 3406.423873175911
Experiment 84/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.014_0.008_0.01_200_2.0_0.034125533211456394.yml
Net PNL quote: -23.971872413729812 | Total Volume: 23184.08880666092
Experiment 85/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.259_0.007_0.014_200_2.0_0.031763705229864075.yml
Net PNL quote: -2.0808584099931795 | Total Volume: 1384.6241533626348
Experiment 86/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.249_0.008_0.016_50_2.0_0.034125533211456394.yml
Net PNL quote: -2.9023151158073275 | Total Volume: 2556.046703185961
Experiment 87/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.011_0.012_0.017_200_1.0_0.01146650573325281.yml
Net PNL quote: -15.278718189404302 | Total Volume: 38416.94058532454
Experiment 88/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.04_0.016_0.022_50_2.0_0.0400920938386012.yml
Net PNL quote: 1.7314689936333123 | Total Volume: 15900.979913929696
Experiment 89/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.042_0.012_0.02_200_2.0_0.042133463224549535.yml
Net PNL quote: -14.557551115324507 | Total Volume: 14380.472065806876
Experiment 90/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.02_0.015_0.02_200_1.0_0.045337016856606044.yml
Net PNL quote: -69.3540460523497 | Total Volume: 29254.32921095332
Experiment 91/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.032_0.014_0.019_50_1.0_0.011716159457667042.yml
Net PNL quote: -0.359047445442367 | Total Volume: 20346.91885647966
Experiment 92/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.017_0.022_0.028_50_2.0_0.017426913099682723.yml
Net PNL quote: -55.7266121246492 | Total Volume: 38523.30484217714
Experiment 93/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.012_0.014_0.019_50_2.0_0.031763705229864075.yml
Net PNL quote: -26.7887241296471 | Total Volume: 44325.069482320076
Experiment 94/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.014_0.028_200_1.0_0.017426913099682723.yml
Net PNL quote: 5.757245783766274 | Total Volume: 24712.03787033278
Experiment 95/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.239_0.012_0.036_50_1.0_0.042133463224549535.yml
Net PNL quote: 3.6618519088005606 | Total Volume: 9909.033056387405
Experiment 96/600: xtreet_bb_binance_perpetual_1m_LSK-USDT_0.0_0.22_0.014_0.021_200_2.0_0.03714784343056587.yml
Net PNL quote: -0.8371368876577864 | Total Volume: 1449.5884369702164
Experiment 97/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.042_0.012_0.02_50_1.0_0.042133463224549535.yml
Net PNL quote: -41.60348255448189 | Total Volume: 26890.5063663492
Experiment 98/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.395_0.015_0.029_50_1.0_0.01966496722505456.yml
Net PNL quote: -6.08750692204083 | Total Volume: 2566.7905621142727
Experiment 99/600: xtreet_bb_binance_perpetual_1m_ZEC-USDT_0.0_0.042_0.02_0.036_50_2.0_0.042133463224549535.yml
Net PNL quote: -19.671582628882053 | Total Volume: 31121.194723434903
Experiment 100/600: xtreet_bb_binance_perpetual_1m_1000SHIB-USDT_0.0_0.032_0.007_0.014_50_1.0_0.031763705229864075.yml
Net PNL quote: -28.48716354170239 | Total Volume: 29928.41322901103
Experiment 101/600: xtreet_bb_binance_perpetual_1m_UNFI-USDT_0.0_0.395_0.015_0.029_50_2.0_0.045337016856606044.yml
Net PNL quote: -6.155123896145208 | Total Volume: 2316.3719706884904
Experiment 102/600: xtreet_bb_binance_perpetual_1m_ADA-USDT_0.0_0.249_0.01_0.016_200_2.0_0.034125533211456394.yml
Net PNL quote: -0.18453932501849596 | Total Volume: 1163.8707168856695
Experiment 103/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.014_0.022_200_1.0_0.04589832515176393.yml
Net PNL quote: -20.097109787984365 | Total Volume: 16273.010550789946
Experiment 104/600: xtreet_bb_binance_perpetual_1m_BAKE-USDT_0.0_0.04_0.016_0.028_50_1.0_0.0400920938386012.yml
Net PNL quote: 5.976248045565633 | Total Volume: 27816.135016966793
Experiment 105/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.046_0.014_0.028_50_1.0_0.017426913099682723.yml
Net PNL quote: -1.8881979358948369 | Total Volume: 30869.016655897543
Experiment 106/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.011_0.017_0.02_200_1.0_0.01146650573325281.yml
Net PNL quote: -41.917443024138855 | Total Volume: 29288.1615154247
Experiment 107/600: xtreet_bb_binance_perpetual_1m_GAS-USDT_0.0_0.298_0.012_0.017_200_1.0_0.01146650573325281.yml
Net PNL quote: -0.30938360878727167 | Total Volume: 1118.6661922303508
Experiment 108/600: xtreet_bb_binance_perpetual_1m_STORJ-USDT_0.0_0.374_0.022_0.028_200_2.0_0.017426913099682723.yml
Net PNL quote: -0.6593802704584153 | Total Volume: 775.3447047331675

In [36]:
import pandas as pd

custom_results = bt_results.copy()
for result in custom_results.values():
    result["results"]["trading_pair"] = result["config"].trading_pair
    result["results"]["config"] = result["config"].dict()
cols_to_show = ["net_pnl_quote", "total_volume", "close_types", "sharpe_ratio", "profit_factor",
                "max_drawdown_usd"]
results_df = pd.DataFrame([result["results"] for result in custom_results.values()])
results_df[cols_to_show]

,net_pnl_quote,total_volume,close_types,sharpe_ratio,profit_factor,max_drawdown_usd
0,-2.75499021,8249.5896749,"{'TAKE_PROFIT': 65, 'TIME_LIMIT': 72}",-0.17687741,0.88259564,-5.86694795
1,-15.16588502,22830.94385212,"{'STOP_LOSS': 3, 'TAKE_PROFIT': 38, 'TIME_LIMI...",-0.41736442,0.86944916,-22.17797244
2,-0.07786584,2034.30545097,"{'TAKE_PROFIT': 38, 'TIME_LIMIT': 62}",-0.20864279,0.99130274,-2.56748382
3,-110.44877394,35274.88246567,"{'STOP_LOSS': 10, 'TAKE_PROFIT': 58, 'TIME_LIM...",-1.39588048,0.52418536,-123.70585871
4,-1.35307041,1654.13917188,"{'TAKE_PROFIT': 46, 'TIME_LIMIT': 41}",-0.69353889,0.83337208,-2.29256304
...,...,...,...,...,...,...
595,-23.65573119,42811.02231,"{'STOP_LOSS': 7, 'TAKE_PROFIT': 60, 'TIME_LIMI...",-0.59818812,0.85559845,-67.45288455
596,-0.91204308,803.22935848,"{'TAKE_PROFIT': 69, 'TIME_LIMIT': 59}",-1.26367499,0.6903144,-0.91161508
597,2.62083906,1145.96045516,"{'TAKE_PROFIT': 25, 'TIME_LIMIT': 51}",1.59862225,1.7117042,-1.44789306
598,-19.97805555,15067.75511811,"{'STOP_LOSS': 6, 'TAKE_PROFIT': 29, 'TIME_LIMI...",-0.70824794,0.74965994,-27.91297241
599,3.47239524,22804.12094402,"{'STOP_LOSS': 13, 'TAKE_PROFIT': 20, 'TIME_LIM...",-0.75684977,1.03672019,-30.70075969

In [37]:
results_df

,net_pnl,net_pnl_quote,total_executors,total_executors_with_position,total_volume,total_long,total_short,close_types,accuracy_long,accuracy_short,total_positions,accuracy,max_drawdown_usd,max_drawdown_pct,sharpe_ratio,profit_factor,win_signals,loss_signals,config,trading_pair
0,-0.00275499,-2.75499021,137,133,8249.5896749,90,43,"{'TAKE_PROFIT': 65, 'TIME_LIMIT': 72}",0.56666667,0.58139535,133,0.57142857,-5.86694795,-0.00586534,-0.17687741,0.88259564,76,57,{'id': 'xtreet_bb_binance_perpetual_1m_XMR-USD...,XMR-USDT
1,-0.01516589,-15.16588502,100,98,22830.94385212,53,45,"{'STOP_LOSS': 3, 'TAKE_PROFIT': 38, 'TIME_LIMI...",0.62264151,0.51111111,98,0.57142857,-22.17797244,-0.02213323,-0.41736442,0.86944916,56,42,{'id': 'xtreet_bb_binance_perpetual_1m_ZEC-USD...,ZEC-USDT
2,-0.00007787,-0.07786584,100,98,2034.30545097,59,39,"{'TAKE_PROFIT': 38, 'TIME_LIMIT': 62}",0.59322034,0.61538462,98,0.60204082,-2.56748382,-0.00256699,-0.20864279,0.99130274,59,39,{'id': 'xtreet_bb_binance_perpetual_1m_BOND-US...,BOND-USDT
3,-0.11044877,-110.44877394,119,116,35274.88246567,67,49,"{'STOP_LOSS': 10, 'TAKE_PROFIT': 58, 'TIME_LIM...",0.6119403,0.6122449,116,0.61206897,-123.70585871,-0.1254214,-1.39588048,0.52418536,71,45,{'id': 'xtreet_bb_binance_perpetual_1m_UNFI-US...,UNFI-USDT
4,-0.00135307,-1.35307041,87,84,1654.13917188,42,42,"{'TAKE_PROFIT': 46, 'TIME_LIMIT': 41}",0.71428571,0.57142857,84,0.64285714,-2.29256304,-0.00229229,-0.69353889,0.83337208,54,30,{'id': 'xtreet_bb_binance_perpetual_1m_ZEC-USD...,ZEC-USDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,-0.02365573,-23.65573119,109,106,42811.02231,57,49,"{'STOP_LOSS': 7, 'TAKE_PROFIT': 60, 'TIME_LIMI...",0.64912281,0.71428571,106,0.67924528,-67.45288455,-0.06734557,-0.59818812,0.85559845,72,34,{'id': 'xtreet_bb_binance_perpetual_1m_GAS-USD...,GAS-USDT
596,-0.00091204,-0.91204308,128,125,803.22935848,73,52,"{'TAKE_PROFIT': 69, 'TIME_LIMIT': 59}",0.56164384,0.61538462,125,0.584,-0.91161508,-0.00091171,-1.26367499,0.6903144,73,52,{'id': 'xtreet_bb_binance_perpetual_1m_ADA-USD...,ADA-USDT
597,0.00262084,2.62083906,76,73,1145.96045516,38,35,"{'TAKE_PROFIT': 25, 'TIME_LIMIT': 51}",0.63157895,0.65714286,73,0.64383562,-1.44789306,-0.0014476,1.59862225,1.7117042,47,26,{'id': 'xtreet_bb_binance_perpetual_1m_BAKE-US...,BAKE-USDT
598,-0.01997806,-19.97805555,91,88,15067.75511811,51,37,"{'STOP_LOSS': 6, 'TAKE_PROFIT': 29, 'TIME_LIMI...",0.60784314,0.45945946,88,0.54545455,-27.91297241,-0.02788021,-0.70824794,0.74965994,48,40,{'id': 'xtreet_bb_binance_perpetual_1m_UNFI-US...,UNFI-USDT
599,0.0034724,3.47239524,63,63,22804.12094402,36,27,"{'STOP_LOSS': 13, 'TAKE_PROFIT': 20, 'TIME_LIM...",0.52777778,0.74074074,63,0.61904762,-30.70075969,-0.03092085,-0.75684977,1.03672019,39,24,{'id': 'xtreet_bb_binance_perpetual_1m_STORJ-U...,STORJ-USDT

In [38]:
import plotly.express as px

# Create a new column with custom hover text
results_df['custom_hover_text'] = results_df.apply(lambda row: f"""
Pair: {row['config']['trading_pair']}
<br>Volume: {row['total_volume']}
<br>PNL: {row['net_pnl_quote']}
<br>Close types: {row['close_types']}

Config:
<br>Id: {row['config']['id']}
<br>BB Length: {row['config']['bb_length']}
<br>BB Std: {row['config']['bb_std']}
<br>Take profit: {row['config']['take_profit']}
<br>Stop loss: {row['config']['stop_loss']}
<br>Time limit: {row['config']['time_limit']}
<br>DCA Spreads: {row['config']['dca_spreads']}
<br>DCA Amounts: {row['config']['dca_amounts_pct']}
""", axis=1)

# Create the scatter plot with the custom hover text
fig = px.scatter(
    results_df,
    x="total_volume",
    y="net_pnl_quote",
    color="trading_pair",  # Color by trading_pair
    hover_data={"custom_hover_text": True},  # Show the custom hover text
    color_discrete_sequence=px.colors.qualitative.Plotly,  # Optional: use a specific color sequence
    title="Net PNL Quote vs. Total Volume by Trading Pair"
)

# Show the figure
fig.show()

In [40]:
results_df.sort_values("net_pnl_quote", ascending=False).iloc[0]

net_pnl                                                                 0.06695389
net_pnl_quote                                                          66.95389485
total_executors                                                                 89
total_executors_with_position                                                   87
total_volume                                                        35578.42437829
total_long                                                                      50
total_short                                                                     37
close_types                      {'STOP_LOSS': 4, 'TAKE_PROFIT': 54, 'TIME_LIMI...
accuracy_long                                                                 0.74
accuracy_short                                                          0.72972973
total_positions                                                                 87
accuracy                                                                0.73563218
max_drawdown_usd                                                      -20.36353375
max_drawdown_pct                                                       -0.02032496
sharpe_ratio                                                            0.86713917
profit_factor                                                           1.71508355
win_signals                                                                     64
loss_signals                                                                    23
config                           {'id': 'xtreet_bb_binance_perpetual_1m_BOND-US...
trading_pair                                                             BOND-USDT
custom_hover_text                \nPair: BOND-USDT\n<br>Volume: 35578.424378293...
Name: 339, dtype: object

In [42]:
config_to_backtest = results_df.sort_values("net_pnl_quote", ascending=False).iloc[0]["config"]
bt_results_r = bt_results[config_to_backtest["id"]]

KeyError: 'xtreet_bb_binance_perpetual_1m_BOND-USDT_0.0_0.011_0.012_0.017_200_2.0_0.03844208396560448'

In [ ]:
bt_results

In [ ]:
bt_results.keys()

In [46]:
import pickle

path = os.path.join(root_path, "research_notebooks", "xtreet_bb", "backtesting_results.pickle")
with open("backtesting_results.pickle", "wb") as f:
    pickle.dump(bt_results, f)

In [34]:

df_r = bt_results_r["df"]
config_r = bt_results_r["config"]
executors_r = bt_results_r["executors"]

In [35]:
bt_results_r["results"]

{'net_pnl': -0.005028775777176928,
 'net_pnl_quote': -5.028775777176928,
 'total_executors': 127,
 'total_executors_with_position': 123,
 'total_volume': 52831.656962605,
 'total_long': 69,
 'total_short': 54,
 'close_types': {'STOP_LOSS': 36, 'TAKE_PROFIT': 43, 'TIME_LIMIT': 48},
 'accuracy_long': 0.5507246376811594,
 'accuracy_short': 0.5555555555555556,
 'total_positions': 123,
 'accuracy': 0.5528455284552846,
 'max_drawdown_usd': -28.99237012667243,
 'max_drawdown_pct': -0.029101643873572274,
 'sharpe_ratio': -0.9481863938914552,
 'profit_factor': 0.9654212282910101,
 'win_signals': 68,
 'loss_signals': 55}

In [30]:
df_r

,timestamp_bt,open_bt,high_bt,low_bt,close_bt,volume_bt,quote_asset_volume_bt,n_trades_bt,taker_buy_base_volume_bt,taker_buy_quote_volume_bt,...,quote_asset_volume,n_trades,taker_buy_base_volume,taker_buy_quote_volume,BBL_50_1.0,BBM_50_1.0,BBU_50_1.0,BBB_50_1.0,BBP_50_1.0,signal
timestamp,,,,,,,,,,,,,,,,,,,,,
2024-08-01 19:55:00,1722542100,0.01524,0.015257,0.015225,0.015225,8788390,133986.739311,396,6589011,100460.350715,...,133986.739311,396,6589011,100460.350715,0.01512736,0.01516692,0.01520648,0.52162161,1.23413112,-1
2024-08-01 19:56:00,1722542160,0.015224,0.015247,0.015222,0.01524,2224175,33886.666222,204,1157934,17640.188463,...,33886.666222,204,1157934,17640.188463,0.01512887,0.01516924,0.01520961,0.53219691,1.37649945,-1
2024-08-01 19:57:00,1722542220,0.015241,0.015251,0.015241,0.015248,1496985,22822.03751,125,918327,13999.284266,...,22822.03751,125,918327,13999.284266,0.01513068,0.01517184,0.015213,0.54258236,1.42517313,-1
2024-08-01 19:58:00,1722542280,0.015247,0.015248,0.015232,0.015245,1801464,27454.533632,181,975247,14864.648896,...,27454.533632,181,975247,14864.648896,0.0151328,0.01517442,0.01521604,0.54854511,1.34792454,-1
2024-08-01 19:59:00,1722542340,0.015245,0.015251,0.015241,0.015242,1553310,23681.630215,175,1239176,18892.443888,...,23681.630215,175,1239176,18892.443888,0.01513488,0.01517684,0.0152188,0.55293723,1.27646858,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-14 02:56:00,1723604160,0.013834,0.013836,0.013833,0.013836,1392403,19263.422124,104,597544,8267.091716,...,19263.422124,104,597544,8267.091716,0.01381571,0.01382706,0.01383841,0.16411596,0.89396428,0
2024-08-14 02:57:00,1723604220,0.013836,0.013836,0.013831,0.013831,825427,11418.502691,117,37633,520.577289,...,11418.502691,117,37633,520.577289,0.01381649,0.01382752,0.01383855,0.15947705,0.65781081,0
2024-08-14 02:58:00,1723604280,0.013831,0.013832,0.013829,0.013831,708353,9797.135429,60,268832,3718.271038,...,9797.135429,60,268832,3718.271038,0.01381683,0.01382778,0.01383873,0.15839605,0.64701412,0
2024-08-14 02:59:00,1723604340,0.013831,0.013832,0.013827,0.013827,400415,5537.710802,65,45611,630.840686,...,5537.710802,65,45611,630.840686,0.01381706,0.01382794,0.01383882,0.15736389,0.45680184,0
2024-08-14 03:00:00,1723604400,0.013828,0.013845,0.013828,0.013845,2066595,28599.943547,258,1859769,25737.708239,...,28599.943547,258,1859769,25737.708239,0.01381714,0.01382828,0.01383942,0.16110741,1.25050326,-1

In [33]:
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np
import plotly.graph_objects as go

from hummingbot.connector.connector_base import TradeType


def get_bt_candlestick_trace(df):
    df.index = pd.to_datetime(df.timestamp, unit='s')
    return go.Scatter(x=df.index,
                      y=df['close'],
                      mode='lines',
                      line=dict(color="blue"),
                      )


def get_pnl_trace(executors):
    pnl = [e.net_pnl_quote for e in executors]
    cum_pnl = np.cumsum(pnl)
    return go.Scatter(
        x=pd.to_datetime([e.close_timestamp for e in executors], unit="s"),
        y=cum_pnl,
        mode='lines',
        line=dict(color='gold', width=2, dash="dash"),
        name='Cumulative PNL'
    )


def get_default_layout(title=None, height=800, width=1800):
    layout = {
        "template": "plotly_dark",
        "plot_bgcolor": 'rgba(0, 0, 0, 0)',  # Transparent background
        "paper_bgcolor": 'rgba(0, 0, 0, 0.1)',  # Lighter shade for the paper
        "font": {"color": 'white', "size": 12},  # Consistent font color and size
        "height": height,
        "width": width,
        "margin": {"l": 20, "r": 20, "t": 50, "b": 20},
        "xaxis_rangeslider_visible": False,
        "hovermode": "x unified",
        "showlegend": False,
    }
    if title:
        layout["title"] = title
    return layout


def add_executors_trace(fig, executors, row, col):
    for executor in executors:
        entry_time = pd.to_datetime(executor.timestamp, unit='s')
        entry_price = executor.custom_info["current_position_average_price"]
        exit_time = pd.to_datetime(executor.close_timestamp, unit='s')
        exit_price = executor.custom_info["close_price"]
        name = "Buy Executor" if executor.config.side == TradeType.BUY else "Sell Executor"

        if executor.filled_amount_quote == 0:
            fig.add_trace(go.Scatter(x=[entry_time, exit_time], y=[entry_price, entry_price], mode='lines',
                                     line=dict(color='grey', width=2, dash="dash"), name=name), row=row, col=col)
        else:
            if executor.net_pnl_quote > Decimal(0):
                fig.add_trace(go.Scatter(x=[entry_time, exit_time], y=[entry_price, exit_price], mode='lines',
                                         line=dict(color='green', width=3), name=name), row=row, col=col)
            else:
                fig.add_trace(go.Scatter(x=[entry_time, exit_time], y=[entry_price, exit_price], mode='lines',
                                         line=dict(color='red', width=3), name=name), row=row, col=col)

        print(f"Entry_time: {entry_time} Exit time: {exit_time}, Exit price: {exit_price}")
    return fig


def create_backtesting_figure(df, executors, config):
    # Create subplots
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True,
                        vertical_spacing=0.02, subplot_titles=('Candlestick', 'PNL Quote'),
                        row_heights=[0.7, 0.3])

    # Add candlestick trace
    fig.add_trace(get_bt_candlestick_trace(df), row=1, col=1)

    # Add executors trace
    fig = add_executors_trace(fig, executors, row=1, col=1)

    # Add PNL trace
    fig.add_trace(get_pnl_trace(executors), row=2, col=1)

    # Apply the theme layout
    layout_settings = get_default_layout(f"Trading Pair: {config['trading_pair']}")
    layout_settings["showlegend"] = False
    fig.update_layout(**layout_settings)

    # Update axis properties
    fig.update_xaxes(rangeslider_visible=False, row=1, col=1)
    fig.update_xaxes(row=2, col=1)
    fig.update_yaxes(title_text="Price", row=1, col=1)
    fig.update_yaxes(title_text="PNL", row=2, col=1)
    return fig


fig = create_backtesting_figure(
    df=df_r,
    executors=executors_r,
    config=config_r.dict())
# df.ta.bbands(length=config.bb_length, std=config.bb_std, append=True)
fig.add_trace(go.Scatter(x=df_r.index,
                         y=df_r[f"BBU_{config_r.bb_length}_{config_r.bb_std}"])
              )
fig.add_trace(go.Scatter(x=df_r.index,
                         y=df_r[f"BBM_{config_r.bb_length}_{config_r.bb_std}"])
              )
fig.add_trace(go.Scatter(x=df_r.index,
                         y=df_r[f"BBL_{config_r.bb_length}_{config_r.bb_std}"])
              )

fig.show()

Entry_time: 2024-08-01 19:55:00 Exit time: 2024-08-01 20:51:00, Exit price: 0.015526
Entry_time: 2024-08-01 23:08:00 Exit time: 2024-08-02 02:22:00, Exit price: 0.015509
Entry_time: 2024-08-02 03:06:00 Exit time: 2024-08-02 06:09:00, Exit price: 0.015358
Entry_time: 2024-08-02 06:09:00 Exit time: 2024-08-02 10:09:00, Exit price: 0.015427
Entry_time: 2024-08-02 10:13:00 Exit time: 2024-08-02 14:13:00, Exit price: 0.0155
Entry_time: 2024-08-02 11:38:00 Exit time: 2024-08-02 14:49:00, Exit price: 0.015238
Entry_time: 2024-08-02 15:43:00 Exit time: 2024-08-02 19:31:00, Exit price: 0.014853
Entry_time: 2024-08-02 19:31:00 Exit time: 2024-08-02 23:31:00, Exit price: 0.014741
Entry_time: 2024-08-02 23:31:00 Exit time: 2024-08-03 00:37:00, Exit price: 0.014529
Entry_time: 2024-08-02 23:44:00 Exit time: 2024-08-03 01:04:00, Exit price: 0.014318
Entry_time: 2024-08-03 01:51:00 Exit time: 2024-08-03 04:33:00, Exit price: 0.014694
Entry_time: 2024-08-03 04:49:00 Exit time: 2024-08-03 08:49:00, Exit price: 0.01462
Entry_time: 2024-08-03 08:52:00 Exit time: 2024-08-03 12:52:00, Exit price: 0.014686
Entry_time: 2024-08-03 13:11:00 Exit time: 2024-08-03 15:43:00, Exit price: 0.014411
Entry_time: 2024-08-03 16:31:00 Exit time: 2024-08-03 16:43:00, Exit price: 0.014181
Entry_time: 2024-08-03 16:46:00 Exit time: 2024-08-03 19:28:00, Exit price: 0.013839
Entry_time: 2024-08-03 19:45:00 Exit time: 2024-08-03 20:07:00, Exit price: 0.013789
Entry_time: 2024-08-03 20:07:00 Exit time: 2024-08-04 00:07:00, Exit price: 0.014192
Entry_time: 2024-08-04 00:07:00 Exit time: 2024-08-04 04:07:00, Exit price: 0.014131
Entry_time: 2024-08-04 04:13:00 Exit time: 2024-08-04 08:04:00, Exit price: 0.013937
Entry_time: 2024-08-04 04:39:00 Exit time: 2024-08-04 08:39:00, Exit price: 0.014048
Entry_time: 2024-08-04 08:39:00 Exit time: 2024-08-04 12:39:00, Exit price: 0.014137
Entry_time: 2024-08-04 09:31:00 Exit time: 2024-08-04 13:31:00, Exit price: 0.014153
Entry_time: 2024-08-04 13:42:00 Exit time: 2024-08-04 14:26:00, Exit price: 0.013853
Entry_time: 2024-08-04 17:50:00 Exit time: 2024-08-04 19:12:00, Exit price: 0.013498
Entry_time: 2024-08-04 20:33:00 Exit time: 2024-08-04 23:12:00, Exit price: 0.013391
Entry_time: 2024-08-05 02:48:00 Exit time: 2024-08-05 05:07:00, Exit price: 0.011929
Entry_time: 2024-08-05 05:07:00 Exit time: 2024-08-05 05:12:00, Exit price: 0.011641
Entry_time: 2024-08-05 05:33:00 Exit time: 2024-08-05 09:33:00, Exit price: 0.011737
Entry_time: 2024-08-05 09:37:00 Exit time: 2024-08-05 10:13:00, Exit price: 0.011459
Entry_time: 2024-08-05 11:47:00 Exit time: 2024-08-05 12:04:00, Exit price: 0.011369
Entry_time: 2024-08-05 12:28:00 Exit time: 2024-08-05 12:37:00, Exit price: 0.011204
Entry_time: 2024-08-05 12:42:00 Exit time: 2024-08-05 12:53:00, Exit price: 0.01113
Entry_time: 2024-08-05 12:55:00 Exit time: 2024-08-05 13:05:00, Exit price: 0.01119
Entry_time: 2024-08-05 13:16:00 Exit time: 2024-08-05 13:30:00, Exit price: 0.011228
Entry_time: 2024-08-05 13:32:00 Exit time: 2024-08-05 13:33:00, Exit price: 0.01148
Entry_time: 2024-08-05 16:56:00 Exit time: 2024-08-05 17:46:00, Exit price: 0.013214
Entry_time: 2024-08-05 19:25:00 Exit time: 2024-08-05 20:08:00, Exit price: 0.013214
Entry_time: 2024-08-05 20:53:00 Exit time: 2024-08-05 21:02:00, Exit price: 0.0133
Entry_time: 2024-08-05 21:02:00 Exit time: 2024-08-05 21:53:00, Exit price: 0.013094
Entry_time: 2024-08-05 21:48:00 Exit time: 2024-08-05 22:08:00, Exit price: 0.013378
Entry_time: 2024-08-05 22:08:00 Exit time: 2024-08-05 23:08:00, Exit price: 0.013626
Entry_time: 2024-08-05 23:23:00 Exit time: 2024-08-06 00:06:00, Exit price: 0.013529
Entry_time: 2024-08-06 00:06:00 Exit time: 2024-08-06 00:17:00, Exit price: 0.013803
Entry_time: 2024-08-06 01:30:00 Exit time: 2024-08-06 05:30:00, Exit price: 0.013812
Entry_time: 2024-08-06 05:30:00 Exit time: 2024-08-06 08:27:00, Exit price: 0.013604
Entry_time: 2024-08-06 06:12:00 Exit time: 2024-08-06 08:34:00, Exit price: 0.013506
Entry_time: 2024-08-06 09:53:00 Exit time: 2024-08-06 12:55:00, Exit price: 0.01325
Entry_time: 2024-08-06 12:55:00 Exit time: 2024-08-06 14:05:00, Exit price: 0.013489
Entry_time: 2024-08-06 14:05:00 Exit time: 2024-08-06 14:19:00, Exit price: 0.013742
Entry_time: 2024-08-06 14:57:00 Exit time: 2024-08-06 16:54:00, Exit price: 0.013796
Entry_time: 2024-08-06 16:54:00 Exit time: 2024-08-06 19:16:00, Exit price: 0.013587
Entry_time: 2024-08-06 17:24:00 Exit time: 2024-08-06 21:24:00, Exit price: 0.013558
Entry_time: 2024-08-06 21:24:00 Exit time: 2024-08-06 23:30:00, Exit price: 0.013452
Entry_time: 2024-08-06 22:25:00 Exit time: 2024-08-07 00:17:00, Exit price: 0.013305
Entry_time: 2024-08-07 00:32:00 Exit time: 2024-08-07 02:24:00, Exit price: 0.013702
Entry_time: 2024-08-07 02:45:00 Exit time: 2024-08-07 04:16:00, Exit price: 0.013785
Entry_time: 2024-08-07 04:16:00 Exit time: 2024-08-07 06:21:00, Exit price: 0.013585
Entry_time: 2024-08-07 04:58:00 Exit time: 2024-08-07 08:58:00, Exit price: 0.013775
Entry_time: 2024-08-07 08:58:00 Exit time: 2024-08-07 12:58:00, Exit price: 0.013768
Entry_time: 2024-08-07 10:51:00 Exit time: 2024-08-07 14:07:00, Exit price: 0.013566
Entry_time: 2024-08-07 15:51:00 Exit time: 2024-08-07 17:18:00, Exit price: 0.013026
Entry_time: 2024-08-07 17:18:00 Exit time: 2024-08-07 20:52:00, Exit price: 0.012783
Entry_time: 2024-08-07 21:49:00 Exit time: 2024-08-07 22:20:00, Exit price: 0.012774
Entry_time: 2024-08-07 22:20:00 Exit time: 2024-08-07 23:20:00, Exit price: 0.012957
Entry_time: 2024-08-07 23:20:00 Exit time: 2024-08-08 00:22:00, Exit price: 0.012766
Entry_time: 2024-08-07 23:31:00 Exit time: 2024-08-08 01:12:00, Exit price: 0.013027
Entry_time: 2024-08-08 01:12:00 Exit time: 2024-08-08 01:48:00, Exit price: 0.013272
Entry_time: 2024-08-08 03:09:00 Exit time: 2024-08-08 07:09:00, Exit price: 0.013315
Entry_time: 2024-08-08 07:09:00 Exit time: 2024-08-08 11:09:00, Exit price: 0.013321
Entry_time: 2024-08-08 11:31:00 Exit time: 2024-08-08 12:32:00, Exit price: 0.013503
Entry_time: 2024-08-08 11:10:00 Exit time: 2024-08-08 12:34:00, Exit price: 0.013594
Entry_time: 2024-08-08 13:32:00 Exit time: 2024-08-08 14:28:00, Exit price: 0.013509
Entry_time: 2024-08-08 15:17:00 Exit time: 2024-08-08 15:58:00, Exit price: 0.013686
Entry_time: 2024-08-08 14:28:00 Exit time: 2024-08-08 16:02:00, Exit price: 0.013781
Entry_time: 2024-08-08 16:50:00 Exit time: 2024-08-08 20:50:00, Exit price: 0.013686
Entry_time: 2024-08-08 20:51:00 Exit time: 2024-08-08 21:46:00, Exit price: 0.013902
Entry_time: 2024-08-08 21:46:00 Exit time: 2024-08-08 22:33:00, Exit price: 0.014155
Entry_time: 2024-08-09 00:01:00 Exit time: 2024-08-09 04:01:00, Exit price: 0.014107
Entry_time: 2024-08-09 04:04:00 Exit time: 2024-08-09 05:04:00, Exit price: 0.013802
Entry_time: 2024-08-09 05:55:00 Exit time: 2024-08-09 09:55:00, Exit price: 0.014062
Entry_time: 2024-08-09 09:55:00 Exit time: 2024-08-09 13:34:00, Exit price: 0.013782
Entry_time: 2024-08-09 14:01:00 Exit time: 2024-08-09 14:31:00, Exit price: 0.013781
Entry_time: 2024-08-09 14:31:00 Exit time: 2024-08-09 17:15:00, Exit price: 0.013988
Entry_time: 2024-08-09 17:15:00 Exit time: 2024-08-09 21:15:00, Exit price: 0.013931
Entry_time: 2024-08-09 17:58:00 Exit time: 2024-08-09 21:58:00, Exit price: 0.014049
Entry_time: 2024-08-09 22:45:00 Exit time: 2024-08-10 00:22:00, Exit price: 0.01418
Entry_time: 2024-08-09 21:58:00 Exit time: 2024-08-10 01:58:00, Exit price: 0.013983
Entry_time: 2024-08-10 00:38:00 Exit time: 2024-08-10 04:38:00, Exit price: 0.013926
Entry_time: 2024-08-10 04:38:00 Exit time: 2024-08-10 08:38:00, Exit price: 0.014022
Entry_time: 2024-08-10 08:38:00 Exit time: 2024-08-10 12:38:00, Exit price: 0.014105
Entry_time: 2024-08-10 12:41:00 Exit time: 2024-08-10 16:41:00, Exit price: 0.014038
Entry_time: 2024-08-10 12:46:00 Exit time: 2024-08-10 16:46:00, Exit price: 0.014043
Entry_time: 2024-08-10 16:46:00 Exit time: 2024-08-10 20:46:00, Exit price: 0.014073
Entry_time: 2024-08-10 17:05:00 Exit time: 2024-08-10 21:05:00, Exit price: 0.014105
Entry_time: 2024-08-10 21:05:00 Exit time: 2024-08-11 01:05:00, Exit price: 0.014145
Entry_time: 2024-08-10 22:01:00 Exit time: 2024-08-11 02:01:00, Exit price: 0.014267
Entry_time: 2024-08-11 02:01:00 Exit time: 2024-08-11 03:04:00, Exit price: 0.014576
Entry_time: 2024-08-11 03:49:00 Exit time: 2024-08-11 07:49:00, Exit price: 0.014384
Entry_time: 2024-08-11 07:51:00 Exit time: 2024-08-11 11:01:00, Exit price: 0.014177
Entry_time: 2024-08-11 08:05:00 Exit time: 2024-08-11 11:23:00, Exit price: 0.014085
Entry_time: 2024-08-11 13:47:00 Exit time: 2024-08-11 15:04:00, Exit price: 0.013719
Entry_time: 2024-08-11 15:04:00 Exit time: 2024-08-11 19:04:00, Exit price: 0.013768
Entry_time: 2024-08-11 19:04:00 Exit time: 2024-08-11 19:33:00, Exit price: 0.013508
Entry_time: 2024-08-11 21:19:00 Exit time: 2024-08-12 01:19:00, Exit price: 0.013548
Entry_time: 2024-08-12 01:19:00 Exit time: 2024-08-12 05:19:00, Exit price: 0.013501
Entry_time: 2024-08-12 01:33:00 Exit time: 2024-08-12 05:33:00, Exit price: 0.013507
Entry_time: 2024-08-12 05:34:00 Exit time: 2024-08-12 07:16:00, Exit price: 0.013306
Entry_time: 2024-08-12 05:44:00 Exit time: 2024-08-12 07:34:00, Exit price: 0.013595
Entry_time: 2024-08-12 07:34:00 Exit time: 2024-08-12 11:01:00, Exit price: 0.01385
Entry_time: 2024-08-12 08:43:00 Exit time: 2024-08-12 11:02:00, Exit price: 0.013924
Entry_time: 2024-08-12 11:02:00 Exit time: 2024-08-12 13:45:00, Exit price: 0.013685
Entry_time: 2024-08-12 12:04:00 Exit time: 2024-08-12 13:45:00, Exit price: 0.013685
Entry_time: 2024-08-12 14:21:00 Exit time: 2024-08-12 18:21:00, Exit price: 0.013768
Entry_time: 2024-08-12 18:22:00 Exit time: 2024-08-12 22:22:00, Exit price: 0.013719
Entry_time: 2024-08-12 22:36:00 Exit time: 2024-08-12 23:18:00, Exit price: 0.013893
Entry_time: 2024-08-12 22:22:00 Exit time: 2024-08-12 23:19:00, Exit price: 0.013976
Entry_time: 2024-08-13 00:02:00 Exit time: 2024-08-13 04:02:00, Exit price: 0.013641
Entry_time: 2024-08-13 04:02:00 Exit time: 2024-08-13 08:02:00, Exit price: 0.013677
Entry_time: 2024-08-13 08:02:00 Exit time: 2024-08-13 12:02:00, Exit price: 0.013629
Entry_time: 2024-08-13 12:02:00 Exit time: 2024-08-13 16:02:00, Exit price: 0.013739
Entry_time: 2024-08-13 13:16:00 Exit time: 2024-08-13 16:32:00, Exit price: 0.013841
Entry_time: 2024-08-13 16:32:00 Exit time: 2024-08-13 20:32:00, Exit price: 0.01387
Entry_time: 2024-08-13 17:23:00 Exit time: 2024-08-13 21:23:00, Exit price: 0.013883
Entry_time: 2024-08-13 21:28:00 Exit time: 2024-08-14 01:28:00, Exit price: 0.013789
Entry_time: 2024-08-13 22:10:00 Exit time: 2024-08-14 02:10:00, Exit price: 0.013828
Entry_time: 2024-08-14 02:23:00 Exit time: 2024-08-14 03:00:00, Exit price: 0.013845